<h1>Homepage</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda possimus quaerat voluptatum cum ullam mollitia necessitatibus culpa adipisci voluptas cumque, rerum fuga, nulla beatae et dicta atque ipsam numquam vero error. Nisi velit nobis aperiam! In repellendus earum minus quam animi quasi consequatur laudantium voluptatibus impedit praesentium, pariatur, distinctio possimus optio nostrum voluptatem aliquam! Obcaecati adipisci ipsum eveniet, ullam unde dolores ipsam tempora odit. Debitis omnis dolores, ipsam amet molestias reiciendis iste quasi ea nesciunt recusandae, necessitatibus laborum voluptas in architecto inventore itaque dolorum rerum quibusdam aliquid possimus dignissimos maxime enim. Vero rerum doloremque eos, mollitia qui quae consequatur amet placeat quam cum quas ullam voluptatum. Eos sed neque labore repellendus corporis, assumenda dolorem quae, eum eaque voluptas maxime reprehenderit a consequatur aperiam ea? Qui ratione culpa laborum explicabo, assumenda fugiat nam at ducimus nobis temporibus non saepe veniam optio doloremque maiores. Mollitia nostrum praesentium molestiae qui labore voluptatum officia aspernatur nulla repellendus saepe placeat tempore rem quis impedit eveniet et obcaecati doloremque, esse nesciunt porro? Sequi laborum placeat aperiam libero, facere dignissimos alias dicta perferendis officiis necessitatibus illo quam quis aliquid magni sint ea eos laudantium eligendi id officia. Quibusdam perferendis, illum, ullam quo unde facere mollitia ipsam odit ab repudiandae maxime atque fuga recusandae reprehenderit, blanditiis architecto odio qui officia illo. Ut iusto optio architecto deleniti et obcaecati, dolor neque. Repudiandae laboriosam laudantium modi inventore quam, neque incidunt perferendis sit aliquid, animi facere! Laboriosam assumenda dolorum repudiandae at error excepturi quos sit. Eaque, beatae. Reiciendis at quis id repellendus maxime accusamus explicabo voluptate, delectus voluptates dolores, facere beatae quae sit! Natus, quidem. Atque adipisci architecto illum, ipsam aliquid quasi, et inventore dolorum dolore unde quibusdam soluta laudantium aut ad, excepturi sequi rem sit doloremque! Minima asperiores vel pariatur? Facilis quod impedit dolore molestiae recusandae modi quaerat harum eos.</p>

<nav class="">
  
  <a class="logo" href="/">La bonne place</a>

  <form action="recherche.php" method="post">
  <label for="recherche">Recherche</label>
<input type="search" name="search" >
<button name="envoyer">Envoyer</button>
</form>
</nav>